// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzftaefstlhiwpfxojpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZnRhZWZzdGxoaXdwZnhvanBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTI5NzAsImV4cCI6MjA3MDc2ODk3MH0.oKm3RFwPP4FUSI9L3S6EpG3b9zzUhzLDdCimAhUGxYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});